"""Write the degraded world as a SQLite file shaped like an old practice-management database.

There is no foreign key anywhere: Animales points at its owner through the owner's NAME.
"""

from __future__ import annotations

import os
import sqlite3
from collections import Counter
from dataclasses import asdict
from pathlib import Path

from .world import REFERENCE_DATE, World

# Stamped into the SQLite header so we can recognise our own files without opening them.
APPLICATION_ID = 0x56445431  # "VDT1"
_SQLITE_MAGIC = b"SQLite format 3\x00"

SCHEMA = """
CREATE TABLE Clientes (
    Codigo        INTEGER PRIMARY KEY,
    Nombre        TEXT,
    Direccion     TEXT,
    Poblacion     TEXT,
    CP            TEXT,
    Telefono      TEXT,
    Telefono2     TEXT,
    Movil         TEXT,
    Email         TEXT,
    Nani          INTEGER,
    FechaAlta     TEXT,
    Observaciones TEXT
);
CREATE TABLE Animales (
    Codigo        INTEGER PRIMARY KEY,
    Cliente       TEXT,
    Nombre        TEXT,
    Especie       TEXT,
    Raza          TEXT,
    Sexo          TEXT,
    FechaNac      TEXT,
    Capa          TEXT,
    Chip          TEXT,
    Baja          INTEGER,
    Observaciones TEXT
);
"""


class ForeignDatabaseError(RuntimeError):
    """The target path holds a database this project did not generate."""


def is_generated_db(path: Path) -> bool:
    """True only for files written by this generator. Reads the 72-byte header, no data."""
    with open(path, "rb") as handle:
        header = handle.read(72)
    if len(header) < 72 or header[:16] != _SQLITE_MAGIC:
        return False
    return int.from_bytes(header[68:72], "big") == APPLICATION_ID


def _legacy_date(value) -> str:
    return value.strftime("%d/%m/%Y")


def client_rows(world: World) -> list[tuple]:
    rows = []
    for c in sorted(world.clients.values(), key=lambda c: c.legacy_codigo):
        household = world.households[c.household_id]

        def column(name: str, c=c) -> str | None:
            return " / ".join(p.raw for p in c.phones_on_file if p.column == name) or None

        rows.append((
            c.legacy_codigo, c.legacy_name, household.address, household.town,
            household.postcode, column("Telefono"), column("Telefono2"), column("Movil"),
            c.email, c.nani_on_file, _legacy_date(c.signup), c.notes or None,
        ))
    return rows


def animal_rows(world: World) -> list[tuple]:
    return [
        (
            p.legacy_codigo, p.legacy_owner_name, p.name, p.legacy_species, p.breed, p.sex,
            _legacy_date(p.born), p.coat, p.chip, int(p.deceased), None,
        )
        for p in sorted(world.pets.values(), key=lambda p: p.legacy_codigo)
    ]


def write_legacy_db(world: World, path: Path) -> None:
    path = Path(path)
    if path.exists() and not is_generated_db(path):
        raise ForeignDatabaseError(
            f"{path} exists and was not generated by vetdesk; refusing to overwrite it. "
            "Choose another --out directory."
        )
    building = path.with_name(f".{path.stem}.building.db")
    building.unlink(missing_ok=True)
    connection = sqlite3.connect(building)
    try:
        connection.executescript(SCHEMA)
        connection.execute(f"PRAGMA application_id = {APPLICATION_ID}")
        connection.executemany(
            "INSERT INTO Clientes VALUES (?,?,?,?,?,?,?,?,?,?,?,?)", client_rows(world)
        )
        connection.executemany(
            "INSERT INTO Animales VALUES (?,?,?,?,?,?,?,?,?,?,?)", animal_rows(world)
        )
        connection.commit()
    finally:
        connection.close()
    os.replace(building, path)


def defect_counts(world: World) -> dict[str, int]:
    counts: Counter[str] = Counter()
    for record in (*world.clients.values(), *world.pets.values()):
        counts.update(record.defects)
    return dict(sorted(counts.items()))


def export_truth(world: World) -> dict:
    """Ground truth for tests and the evaluation harness. The agent side never reads this."""
    return {
        "schema_version": 1,
        "reference_date": REFERENCE_DATE.isoformat(),
        "config": asdict(world.config),
        "clients": [
            {
                "client_id": c.client_id,
                "legacy_codigo": c.legacy_codigo,
                "legacy_name": c.legacy_name,
                "given_name": c.given,
                "surname1": c.surname1,
                "surname2": c.surname2,
                "surname2_on_file": c.surname2_on_file,
                "language": c.language,
                "household_id": c.household_id,
                "current_phones": world.current_phones(c),
                "phones_on_file": [
                    {"number": p.number, "column": p.column, "status": p.status}
                    for p in c.phones_on_file
                ],
                "pet_ids": c.pet_ids,
                "nani_on_file": c.nani_on_file,
                "defects": c.defects,
            }
            for c in world.clients.values()
        ],
        "pets": [
            {
                "pet_id": p.pet_id,
                "legacy_codigo": p.legacy_codigo,
                "legacy_owner_name": p.legacy_owner_name,
                "name": p.name,
                "species": p.species,
                "breed": p.breed,
                "deceased": p.deceased,
                "owner_client_id": p.owner_id,
                "linked_client_ids": p.linked_client_ids,
                "defects": p.defects,
            }
            for p in world.pets.values()
        ],
        "stale_phone_holders": world.stale_holders,
        "planted": world.planted,
        "defect_counts": defect_counts(world),
    }
