"""Adapter for the legacy database: Clientes and Animales, linked by the owner's name."""

from __future__ import annotations

import sqlite3
from collections import Counter
from pathlib import Path

from ..dbguard import ForeignDatabaseError, is_generated_db
from ..names import given_name_forms
from .models import Animal, Client, Clinic, DataIssue
from .normalize import (
    fold,
    name_key,
    normalize_species,
    osa_distance,
    parse_name,
    parse_phones,
    spelling_key,
)

PHONE_COLUMNS = ("Telefono", "Telefono2", "Movil")


class LegacySqliteSource:
    """Reads the legacy schema read-only and resolves the name-based links."""

    def __init__(self, path: Path | str) -> None:
        self.path = Path(path)

    def load(self) -> Clinic:
        if not self.path.exists():
            raise FileNotFoundError(self.path)
        if not is_generated_db(self.path):
            # House rule: only synthetic databases generated by this project are ever opened.
            raise ForeignDatabaseError(
                f"{self.path} was not generated by vetdesk; refusing to open it."
            )
        connection = sqlite3.connect(f"file:{self.path}?mode=ro", uri=True)
        connection.row_factory = sqlite3.Row
        try:
            client_rows = connection.execute("SELECT * FROM Clientes ORDER BY Codigo").fetchall()
            animal_rows = connection.execute("SELECT * FROM Animales ORDER BY Codigo").fetchall()
        finally:
            connection.close()

        issues: list[DataIssue] = []
        clients = {row["Codigo"]: _client(row, issues) for row in client_rows}
        animals = _animals(animal_rows, clients, issues)
        clinic = Clinic(clients, animals, issues)
        _audit(clinic)
        return clinic


def _client(row: sqlite3.Row, issues: list[DataIssue]) -> Client:
    code = row["Codigo"]
    phones: list[str] = []
    for column in PHONE_COLUMNS:
        numbers, unreadable = parse_phones(row[column])
        phones += [n for n in numbers if n not in phones]
        if unreadable:
            detail = f"{column}={row[column]!r}"
            issues.append(DataIssue("phone_unreadable", "Clientes", code, detail))
    name = parse_name(row["Nombre"])
    if name is None:
        issues.append(DataIssue("name_unreadable", "Clientes", code, repr(row["Nombre"])))
    if not phones:
        issues.append(DataIssue("no_phone", "Clientes", code, "no usable phone number"))
    return Client(
        code=code,
        raw_name=row["Nombre"] or "",
        name=name,
        phones=tuple(phones),
        animals_declared=row["Nani"],
        town=row["Poblacion"],
        email=row["Email"],
    )


def _animals(
    rows: list[sqlite3.Row], clients: dict[int, Client], issues: list[DataIssue]
) -> dict[int, Animal]:
    by_key: dict[str, list[int]] = {}
    for client in clients.values():
        by_key.setdefault(name_key(client.raw_name), []).append(client.code)

    animals: dict[int, Animal] = {}
    for row in rows:
        code, owner_raw = row["Codigo"], row["Cliente"] or ""
        key = name_key(owner_raw)
        owners, link = by_key.get(key, []), "exact"
        if not owners:
            # The owner's name was retyped at some point: accept a one-keystroke difference.
            typed = spelling_key(owner_raw)
            owners = [c.code for c in clients.values()
                      if osa_distance(typed, spelling_key(c.raw_name), 1) <= 1]
            link = "fuzzy" if owners else "none"
        if not owners:
            issues.append(DataIssue("owner_not_found", "Animales", code, repr(owner_raw)))
        elif len(owners) > 1:
            issues.append(DataIssue("owner_ambiguous", "Animales", code,
                                    f"{owner_raw!r} matches clients {sorted(owners)}"))
        elif link == "fuzzy":
            match = clients[owners[0]].raw_name
            issues.append(DataIssue("owner_fuzzy", "Animales", code, f"{owner_raw!r} ~ {match!r}"))
        animals[code] = Animal(
            code=code,
            name=row["Nombre"] or "",
            species=normalize_species(row["Especie"]),
            breed=row["Raza"],
            deceased=bool(row["Baja"]),
            owner_raw=owner_raw,
            owner_codes=tuple(sorted(owners)),
            link=link,
        )
    return animals


def _audit(clinic: Clinic) -> None:
    """Record the inconsistencies that matter when deciding who is calling."""
    issues = clinic.issues
    names = Counter(name_key(c.raw_name) for c in clinic.clients.values())
    givens = Counter(fold(c.name.given) for c in clinic.clients.values() if c.name)
    common_givens = [given for given, count in givens.items() if count >= 3]
    for client in clinic.clients.values():
        if names[name_key(client.raw_name)] > 1:
            issues.append(DataIssue("name_duplicate", "Clientes", client.code, client.raw_name))
        sharing = {c.code for n in client.phones for c in clinic.clients_by_phone(n)}
        if len(sharing) > 1:
            issues.append(DataIssue("phone_shared", "Clientes", client.code,
                                    f"shares a number with {sorted(sharing - {client.code})}"))
        given = fold(client.name.given) if client.name else ""
        if given and givens[given] == 1 and len(given_name_forms(given)) == 1:
            # A given name nobody else has, one keystroke from a common one: a likely typo,
            # and one the resolver will not forgive. Worth fixing at the source.
            lookalike = next((g for g in common_givens if osa_distance(given, g, 1) == 1), None)
            if lookalike:
                issues.append(DataIssue("given_name_suspect", "Clientes", client.code,
                                        f"{client.name.given!r} looks like {lookalike!r}"))
        own = [a for a in clinic.animals_of(client.code) if len(a.owner_codes) == 1]
        ambiguous = len(clinic.animals_of(client.code)) - len(own)
        if not ambiguous and client.animals_declared != len(own):
            issues.append(DataIssue("animal_count_mismatch", "Clientes", client.code,
                                    f"Nani={client.animals_declared}, found {len(own)}"))
